### ISSUE TITLE
RW hint rounding

### ISSUE THREAD

**Issue by yoavweiss** [igrigorik/http-client-hints#38]
The `RW` hint is defined as an int, but it's not well defined how the rounding of that value (when using `sizes` based value) should be rounded.
I don't think it really matters if we define it as round-down/up/closest, as long as it's well defined and browsers are consistent.

**Comment by ejthurgo** [comment]
I'm not a browser rendering expert, but I'd probably propose a round up. If RW is detected as a non-int ( e.g. 200.3 ). Guessing it would be better to ceiling, server deliver 201 or above and allow the browser to rescale down?

**Comment by yoavweiss** [comment]
Hmm, from that perspective, rounding down may make more sense, since we can avoid the downsizing in such cases.

**Comment by resrcit-dev** [comment]
I assumed (perhaps wrongly) that in a 200.3 scenario, delivering an image of 200 would require an upscale. Given that in terms of image quality, downscale trumps upscale, I thought ceiling would be better than floor. If however no upscale would take place - I absolutely agree.

**Comment by igrigorik** [comment]
@yoavweiss @resrcit-dev what does the layout engine do? If the layout box is 200.3, does it make it 200 or 201px?

**Comment by yoavweiss** [comment]
I assume it makes it 200, but I'll make sure.

**Comment by yoavweiss** [comment]
Oh my...
http://jsbin.com/sivafanuru/1/edit?html,console,output

Chrome is rounding to the nearest integer value where 0.5 is rounded down.
Firefox is rounding to the nearest integer value where 0.5 is rounded up.
Safari is always rounding down.

**Comment by ejthurgo** [comment]
I guess the obvious solution is to mirror the rounding in the layout engine, rather than the CH spec specifically say round up or round down then.

**Comment by igrigorik** [comment]
@yoavweiss IE? :)

@ejthurgo the issue with that is that we'd unnecessarily fragment the HTTP cache with "off by 1 pixel" assets. I'd much prefer that we handle this consistently across different engines. Otherwise, we'd burden servers with yet more UA-sniffing logic to account for.

That said, not sure how feasible it is to rationalize all this across the different engines.

 /cc @natduca @rbyers @marcoscaceres @bzbarsky @sicking fyi..

**Comment by ejthurgo** [comment]
Presumably you're talking about caching in reverse proxies rather than browser - but yes, understood, not something I'd yet considered. I guess then, whichever way the rationalization goes there is going to have to be some upscaling/downscaling in some browsers, preferably down, which implies a round up?

**Comment by bzbarsky** [comment]
I'm not sure what the testcase linked in https://github.com/igrigorik/http-client-hints/issues/38#issuecomment-97841735 is supposed to be showing...  It renders identically for me in Firefox and Chrome, Firefox logs 0 three times, Chrome logs nothing.

**Comment by yoavweiss** [comment]
Here's a [cleaner test case](http://jsbin.com/yerehesahu/1/edit?html,console,output)

In here we see Firefox always rounding down, while Chrome and Safari are rounding up 150.5, but rounding down 150.8 and 150.2.
I'd test IE if I have a VM handy...

IMO:

* This behavior should be specced (and maybe it is, but I failed to find where)
* We should fix browsers so that they'd all render these images identically based on said spec
* Don't think we should block RW implementation on that.

**Comment by bzbarsky** [comment]
Hmm.  Looks like per HTML spec, the `width` attribute of `<img>` is supposed to be parsed as a floating point number.  Did this change at some point?  That's not what Gecko does: we just parse it as an integer, discarding anything that's not a digit.  This has nothing to do with RW, afaict.

But also, that testcase uses `.clientWidth`, which does its own rounding to integer values which might be unrelated to anything else that's going on.  If you examine `.getBoundingClientRect().width` you will actually get fractional answers in Chrome, for example.  Are you trying to examine the rounding that `.clientWidth` performs, or something else?

**Comment by bzbarsky** [comment]
Oh, and the spec of http://dev.w3.org/csswg/cssom-view/#dom-element-clientwidth does of course need adjusting to define the rounding.

**Comment by igrigorik** [comment]
@yoavweiss fwiw: https://remote.modern.ie/ -- running your test case through it with IE11 shows "150" for all three. /cc @tobint @toddreifsteck

Also, I agree, there is no reason to block RW on this stuff: we should file appropriate bugs to get this addressed in various engines, and the spec, and.. add a note in CH for rounding strategy based on whatever goes into the CSSOM spec.

**Comment by yoavweiss** [comment]
You're right of course. clientWidth is irrelevant here.

What I'm trying to see is how image rendering of fractional pixel images works in different browsers, in order to see what should be the rounding behavior for RW.

OTOH, when thinking of it, since the image resolution delivered by the server needs to take into account both RW and DPR, maybe it doesn't make sense to round it at all? e.g. for RW=212.5 and DPR=2 the server-side logic probably want to send out images that are 425 pixels wide. Rounding either way will mean either downscaling or upscaling.

**Comment by igrigorik** [comment]
> OTOH, when thinking of it, since the image resolution delivered by the server needs to take into account both RW and DPR, maybe it doesn't make sense to round it at all? e.g. for RW=212.5 and DPR=2 the server-side logic probably want to send out images that are 425 pixels wide. Rounding either way will mean either downscaling or upscaling.

It still seems odd to me to advertise fractional pixels, even if we account for DPR. Further, regardless of whether it's a good idea or not.. if we agree that browsers should converge on the same final (integer) value, then it seems to fall out that we should also advertise that same (integer) value via RW?

**Comment by toddreifsteck** [comment]
@gregwhitworth, can you take a look?

**Comment by yoavweiss** [comment]
> It still seems odd to me to advertise fractional pixels, even if we account for DPR. Further, regardless of whether it's a good idea or not.. if we agree that browsers should converge on the same final (integer) value, then it seems to fall out that we should also advertise that same (integer) value via RW?

Browser should converge on a final CSS pixel integer value, but images are rendered in integer device pixels. Now, `RW` reports CSS pixels, and I agree that arbitrarily accurate fractional number may not make sense, but ideally the browser should report an RW that represents the integer device pixels in fractional CSS pixels.

**Comment by igrigorik** [comment]
@yoavweiss ok, I'm with you.. but then we also have the complication of irrational numbers that the server would have to deal with - e.g. my DPR is 3x, RW reports 100.33..333? In other words, the server would have to implement rounding logic, and we'd have to cross our fingers that they get it right. FWIW, I'm still thinking it might be easier and better for RW to report an int value.. let's just pick a strategy that will yield the closest match to layout size, and go with it?

**Comment by atanassov** [comment]
@yoavweiss @igrigorik at this point all browser engines support subpixel layout and to some extend rendering. There is a difference in the precision at which this is done - for example we use 1/100px where Blink I believe is 1/64px and Geko 1/60px (I might be off on these). This variance leads to inevitable differences in the accumulation of rounding errors during layout but in the majority of cases it doesn't matter. 
During rendering there are different approaches that most of us take in order to improve the quality (think sharpness) of the visuals. This is done mostly for backgrounds, borders, text underlines and images among others. Rendering such primitives yields best results when they are snapped on the pixel grid (see http://jsfiddle.net/mt30x8uo/ as an example). This snapping is quite involved and I wouldn't want to go into details nor very important in this context.
With all of that said, I'm with @igrigorik that it would be best to keep the RW values as integers because during rendering they will get snapped (and resampled) anyway. 
On the question of how do we go about rounding - that's not as straight forward... rounding an image of size 2x2 (say used for background tiling) will have enormous impact if done wrong compared to one that's 2000x2000 where the human eye can hardly tell the difference.
If you have to choose only one option, for layout purpose flooring is always the safe bet and for rendering you want the higher fidelity image so rounding or even ceiling makes more sense. Perhaps rounding can be different based on the size ...? ranges [1px - 10px], [10px - 100] etc..

**Comment by igrigorik** [comment]
@atanassov thanks, this is really helpful. FWIW, I'm inclined to keep it simple and avoid ranges. I'm +1 on ceiling.

**Comment by yoavweiss** [comment]
I'm sold on ceiling, since any alternative is just too complex and varies between browsers.
