### ISSUE TITLE
Split RW/Width

### ISSUE THREAD

**Issue by yoavweiss** [igrigorik/http-client-hints#47]
During the [webkit-dev](https://lists.webkit.org/pipermail/webkit-dev/2015-May/027424.html) discussion, a proposal was raised to split the "resource-width that falls back to viewport-width" hint to two distinct hints that would indicate "Viewport Width" and "Resource width" separately.

* Is that something that would be worth while?
* When the browser has the resource width, should it send both or only one?
* What should the Accept-CH opt-in be?

**Comment by igrigorik** [comment]
In reverse order... 

* The Accept-CH is simple: you explicitly opt-in for each hint you'd like to receive, and since viewport width and resource width are separate hints, they require separate opt-in flags.
* We should send both, they're independent hints.
* I do think it's worth separating them. We do know that many developers want to know viewport-width on the server, and that may be used as a separate signal from resource display width.
